### ISSUE TITLE
iOS Example

### ISSUE THREAD

**Issue by genecyber** [stephenlb/webrtc-sdk#16]
I'd like to see  an example of a native implementation I could deploy to iOS

A fallback to pubnub non rtc would be nice in the even that I'm running an app in a browser that doesn't support getusermedia (iOS webview)

**Comment by evilantnie** [comment]
I'd like to see this too, the documentation is a little misleading since there is no out-of-the-box support for iOS in this SDK.  I'm assuming that the ICE negotiation is pretty standard so it may not be a huge leap to leverage something like https://github.com/ISBX/apprtc-ios and wire it up to pubnub's implementation. I may try that and see where it lands me but it would be nice if @stephenlb could provide a little direction for us.

**Comment by stephenlb** [comment]
iOS not supported.  Use https://xirsys.com/ or https://www.sinch.com/
